// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_rank from "./routes/api/rank.ts";
import * as $index from "./routes/index.jsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/rank.ts": $api_rank,
    "./routes/index.jsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
